server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ietm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    druid:
          filters:
#            - stat
#            - wall
#            - log4j
          stat-view-servlet:
            login-username: root
            login-password: root
          pool-prepared-statements: true
          max-open-prepared-statements: 100
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths:
            - /**
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.com.icloud.test.mapper  